### ISSUE TITLE
"Error! Bad return status for module build on kernel: 7.2.0-rc1-1-MANJARO (x86_64)" or "zenpower_core.c:755:37: error: implicit declaration of function ‘cpuid_ecx’"

### ISSUE THREAD

**Issue by entropy2eat** [mattkeenan/zenpower5#13]
Hi! Thank you for the tool!

When I was trying to install 7.2-rc1 kernel version I got the error:
```
...
(3/6) Install DKMS modules
==> ERROR: Missing 7.2.0-rc1-1-MANJARO kernel headers for module zenpower5/0.5.0.r3.g66871d8.
(4/6) Updating linux initcpios...
...
```
but during the `linux72-headers` installation I got new error:
```
...
(3/4) Install DKMS modules
==> dkms install --no-depmod zenpower5/0.5.0.r3.g66871d8 -k 7.2.0-rc1-1-MANJARO

Error! Bad return status for module build on kernel: 7.2.0-rc1-1-MANJARO (x86_64)
Consult /var/lib/dkms/zenpower5/0.5.0.r3.g66871d8/build/make.log for more information.
==> WARNING: `dkms install --no-depmod zenpower5/0.5.0.r3.g66871d8 -k 7.2.0-rc1-1-MANJARO' exited 10
(4/4) Checking which packages need to be rebuilt
```
The noted log content:
```
DKMS (dkms-3.4.1) make.log for zenpower5/0.5.0.r3.g66871d8 for kernel 7.2.0-rc1-1-MANJARO (x86_64)
<EDIT: date and time here>

Building module(s)
# command: make -j16 KERNELRELEASE=7.2.0-rc1-1-MANJARO TARGET=7.2.0-rc1-1-MANJARO CFLAGS_MODULE+=
make[1]: Entering directory '/usr/lib/modules/7.2.0-rc1-1-MANJARO/build'
make[2]: Entering directory '/var/lib/dkms/zenpower5/0.5.0.r3.g66871d8/build'
  CC [M]  zenpower_core.o
  CC [M]  zenpower_svi2.o
  CC [M]  zenpower_rapl.o
  CC [M]  zenpower_temp.o
zenpower_core.c: In function ‘zenpower_probe’:
zenpower_core.c:755:37: error: implicit declaration of function ‘cpuid_ecx’ [-Wimplicit-function-declaration]
  755 |         data->nodes_per_cpu = 1 + ((cpuid_ecx(0x8000001E) >> 8) & 0b111);
      |                                     ^~~~~~~~~
make[4]: *** [/usr/lib/modules/7.2.0-rc1-1-MANJARO/build/scripts/Makefile.build:289: zenpower_core.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/lib/modules/7.2.0-rc1-1-MANJARO/build/Makefile:2184: .] Error 2
make[2]: *** [/usr/lib/modules/7.2.0-rc1-1-MANJARO/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/zenpower5/0.5.0.r3.g66871d8/build'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/7.2.0-rc1-1-MANJARO/build'
make: *** [Makefile:36: modules] Error 2

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------
```
May be it somehow correlated with the ["The stats look pretty normal, although another AMD header drop means that a third of the patch is just various AMD GPU register definitions."](https://www.phoronix.com/news/Linux-7.2-rc1-Released)

<hr>

```
$ pacman -Qi zenpower5-dkms-git | grep -E "Name|Version|Description|URL"
Name            : zenpower5-dkms-git
Version         : 0.5.0.r3.g66871d8-1
Description     : Linux kernel driver for reading sensors for AMD Zen family CPUs
URL             : https://github.com/mattkeenan/zenpower5
```

```
Operating System: Manjaro Linux 
KDE Plasma Version: 6.7.1
KDE Frameworks Version: 6.27.0
Qt Version: 6.11.1
Kernel Version: 7.1.2-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7730U with Radeon Graphics
Memory: 64 GiB of RAM (60.7 GiB usable)
Graphics Processor: AMD Radeon Graphics
...
```

**Comment by jastreb** [comment]
confirmed for kernel 7.2 on cachyos same error when trying to install RC

```
zenpower_core.c:755:30: error: call to undeclared function 'cpuid_ecx'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration] 755 | data->nodes_per_cpu = 1 + ((cpuid_ecx(0x8000001E) >> 8) & 0b111);
```

https://paste.cachyos.org/p/c3f3084


seems to be[ related to this function
](https://github.com/mattkeenan/zenpower5/blob/66871d8e59c3741e00de2eb1f61c3b64263ed10b/zenpower_core.c#L755)

**Comment by pallaswept** [comment]
Needs the include added to zenpower_core.c, like so:
```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(7, 2, 0)
#include <asm/cpuid/api.h>
#endif
```
See similar for zenpower3:
https://github.com/AliEmreSenel/zenpower3/commit/faeb180492209db51a93ed24b30b2d3b2acf785d

**Comment by simona70** [comment]
no fix?
